// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('FUNC_017', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('FUNC_017', async function() {
    await driver.get("https://e-energy.netlify.app/")
    await driver.wait(until.elementTextIs(await driver.findElement(By.xpath("//button[3]")), 'QUẢN LÝ HÓA ĐƠN'), 30000)
    await driver.findElement(By.xpath("//button[3]")).click()
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.name("customerCode")).click()
    await driver.findElement(By.name("customerCode")).sendKeys("PE56465S5")
    await driver.findElement(By.name("newIndicator")).click()
    await driver.findElement(By.name("newIndicator")).sendKeys("400")
    await driver.findElement(By.name("oldIndicator")).click()
    await driver.findElement(By.name("oldIndicator")).sendKeys("300")
    await driver.findElement(By.name("actualElectric")).click()
    await driver.findElement(By.name("actualElectric")).sendKeys("100")
    await driver.findElement(By.name("signinDate")).click()
    await driver.findElement(By.name("signinDate")).sendKeys("12022023")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    assert(await driver.findElement(By.css(".MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(1)")).getText() == "64646dea6967fc10a5dde152")
  })
})
