// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('FUNC_008', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('FUNC_008', async function() {
    await driver.get("https://e-energy.netlify.app/")
    await driver.findElement(By.xpath("//button[2]")).click()
    await driver.wait(until.elementTextIs(await driver.findElement(By.xpath("//button[2]")), 'QUẢN LÝ NGƯỜI DÙNG'), 30000)
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(1) .PrivateSwitchBase-input")).click()
    assert(await driver.findElement(By.xpath("//td[4]")).getText() == "Quản trị viên")
  })
})
