// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("https://e-energy.netlify.app/")
    await driver.findElement(By.css(".css-1yxmbwk")).click()
    await driver.findElement(By.css(".MuiButton-containedPrimary")).click()
  })
})
