// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('FUNC_017', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('FUNC_017', async function() {
    await driver.get("https://e-energy.netlify.app/")
    await driver.wait(until.elementTextIs(await driver.findElement(By.xpath("//button[3]")), 'QUẢN LÝ HÓA ĐƠN'), 30000)
    await driver.findElement(By.xpath("//button[3]")).click()
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.css(".css-5zrdtn")).click()
    assert(await driver.findElement(By.xpath("//p[contains(.,\'Không được để trống!\')]")).getText() == "Không được để trống!")
  })
})
