// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('FUNC_008', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('FUNC_008', async function() {
    await driver.get("https://e-energy.netlify.app")
    await driver.findElement(By.css(".MuiButton-contained")).click()
    await driver.findElement(By.css(".css-5zrdtn")).click()
    assert(await driver.findElement(By.id(":r3:-helper-text")).getText() == "Không được để trống!")
  })
})
