// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("https://e-energy.netlify.app/")
    await driver.wait(until.elementTextIs(await driver.findElement(By.xpath("//button[2]")), 'TÍNH TIỀN ĐIỆN'), 30000)
    await driver.findElement(By.xpath("//button[2]")).click()
    await driver.findElement(By.name("indicator")).click()
    await driver.findElement(By.name("indicator")).sendKeys("100")
    await driver.findElement(By.css(".MuiButton-root:nth-child(3)")).click()
    assert(await driver.findElement(By.css(".MuiTypography-root:nth-child(10)")).getText() == "Tổng cộng tiền thanh toán: 187660 vnd")
  })
})
